language: scala
before_script:
  - export PROJECT_VERSION="`egrep -os -e '([0-9]\.)+[0-9](-\w+)?' version.sbt`" && echo Project Version is $PROJECT_VERSION
  - export ARTIFACT="marathon-$PROJECT_VERSION.tgz"
  - export BROCCOLI_ENV="production"
  - pushd src/main/resources/assets && npm run clean && npm install -g broccoli-cli && npm install && npm run build && popd
jdk:
  - openjdk6
scala:
  - 2.11.2
env:
  global:
    - ARTIFACTS_AWS_REGION=us-east-1
    - ARTIFACTS_S3_BUCKET=downloads.mesosphere.io
    # IAM User: MarathonRelease
    - secure: Ujj0GCEtGTs5jJneR41XFKgI9i9FXzkka6EsmI7BPOcJUfdp7NhGtxPsmMdheQZA725HQf5ES8ve6CzKuJbCdJ4IJx6HKJp1xgLDdGshcYW8kUha+sYeh9/vpagaZoNYJ9ArpdEHP7yJbKmga79pyoPAp3NbkY5QG8onaJCphZw=
    - secure: MKUdKA6AbtETQvYkebXWbA+1zsQqG81d9bNuBlOc1vOt+whMAjEGdgZ/aqokXWJzNMFlaBdSeDfhS48+ibYUh2mW2N7XRwwTotVUcEAXdkoYYlfxfkTeHO2anadQVr/VYvLhDGSG+UCyEgTea1BmsqR2jutw/IIn2zS+mKALKt8=
script: sbt assembly
after_success:
  # Pin to Faraday 0.8.9 due to:
  # https://github.com/travis-ci/travis-artifacts/issues/23
  - gem install --no-rdoc --no-ri --version 0.8.9 faraday
  # Pin to travis-artifacts 0.2.2 to fix hostname mismatch errors with 0.3.0
  - gem install --no-rdoc --no-ri --version 0.2.2 travis-artifacts
  - bin/build-distribution
  # Prepend a marathon version dir to the tarball elements (requires GNU tar)
  - |
    tar -czv -f "$ARTIFACT" --transform "s,,marathon-$PROJECT_VERSION/," \
      Dockerfile README.md LICENSE bin examples docs \
      target/scala-2.11/marathon-assembly-*.jar
  - shasum --binary --algorithm 256 "$ARTIFACT" > "$ARTIFACT".sha256
  - travis-artifacts upload --path "$ARTIFACT" --target-path marathon/"$TRAVIS_BRANCH"/
  - travis-artifacts upload --path "$ARTIFACT".sha256 --target-path marathon/"$TRAVIS_BRANCH"/
notifications:
  slack:
    secure: apUObVUa/OhaTEvoYw3oM1ZTTT0LtYolofJYqnWiBOusc6qgMlK2rfk5kod7vDn33cSKwGhFcyVrrFCn2qxuvYUWCpK4Yo6Hj7KIjoqMi9yHLHXAAWIfAFNMlCdaUGjlHLWn757rBkbuQUDVH8HmB6Vc3J3sybTbiFmMDP1cEVo=
