defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "docs"
    values:
      layout: docs
      tab: docs

sass:
  sass_dir: _sass
  style: :compressed

baseurl: "/marathon"
highlighter: rouge
lsi: false
markdown: kramdown
kramdown:
  extensions: [with_toc_data, tables]
safe: true
source: .
exclude: [vendor/bundle]
repository: mesosphere/marathon
